name = "tokenish-tokex-clock"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "TOKEX_CLOCK"
class_name = "TokexClock"

[[migrations]]
tag = "v1"
new_classes = ["TokexClock"]
